sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y build-essential libtool autoconf
  - sudo apt-get install -qq -y libgmp-dev libmpfr-dev libqd-dev
  - sudo apt-get install -qq -y python-pip python-dev
  - sudo apt-get install -qq -y python-flake8

install:
  - ./install-dependencies.sh $VIRTUAL_ENV
  - pip install Cython
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py -q install

before_script:
  - "flake8 --max-line-length=120 --max-complexity=16 --ignore=E22,E241 src"
  
script:
  - LD_LIBRARY_PATH="$VIRTUAL_ENV/lib" py.test
  - LD_LIBRARY_PATH="$VIRTUAL_ENV/lib" python -m doctest src/fpylll/*.pyx src/fpylll/fplll/*.pyx

notifications:
  on_success: change
  on_failure: always

