language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y build-essential libtool autoconf
  - sudo apt-get install -qq -y libgmp-dev libmpfr-dev libqd-dev
  - sudo apt-get install -qq -y python-pip python-dev

install:
  - ./install-dependencies.sh $VIRTUAL_ENV
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py -q install

  
script:
  - LD_LIBRARY_PATH="$VIRTUAL_ENV/lib" py.test

notifications:
  on_success: change
  on_failure: always

